version: '3'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_USER=netpower
      - MARIADB_DATABASE=db
      - MARIADB_ROOT_PASSWORD=n3v0rN
      - MARIADB_PASSWORD=unst0p@ble
    networks:
      - internal
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./wordpress:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=netpower
      - WORDPRESS_DATABASE_NAME=db
      - WORDPRESS_DATABASE_PASSWORD=unst0p@ble
    networks:
      - internal
  phpfpm:
    build:
      context: .
      dockerfile: docker-entrypoint.sh
    volumes:
      - ./wordpress:/var/www/html
      - ./docker-entrypoint.sh:/entrypoint.sh
    working_dir: /var/www/html
    networks:
      - internal
networks:
  internal:
    driver: bridge